project:
  type: website
  
resources:
  - "data/**"

website:
  title: "Anatoly Tsyplenkov"
  description: "Personal website of Anatoly Tsyplenkov"
  site-url: https://anatolii.nz
  repo-url: https://github.com/atsyplenkov/quarto-blog
  open-graph: true
  favicon: favicon.svg
  twitter-card: 
    creator: "@atsyplen"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: "index.qmd"
        text: Home
      - href: "about.qmd"
      - href: "talks.qmd"
        text: Talks
      - href: "papers.qmd"
      - href: "software.qmd"
      # - href: "app.qmd"
    right:
      - icon: github
        href: https://github.com/atsyplenkov
      - icon: mastodon
        href: https://fosstodon.org/@atsyplenkov
      - text: "{{< iconify simple-icons:bluesky >}}"
        href: https://bsky.app/profile/anatolii.nz
      - icon: twitter
        href: https://twitter.com/atsyplen
      - icon: linkedin
        href: https://www.linkedin.com/in/atsyplenkov/
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=IcwW-WAAAAAJ&hl=en
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Anatoly Tsyplenkov</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>
    center: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
      <span><a rel="me" href="https://fosstodon.org/@atsyplenkov">Mastodon</a></span>
    right: |
      <span class="faux-block"> [{{< fa solid rss >}}](/index.xml)</span>
      <span class="faux-block"> [{{< fa solid envelope >}}](mailto:atsyplenkov@gmail.com)</span>

format:
  html:
    theme: 
      - ath.scss
    toc: true
    toc-depth: 4
    html-math-method: katex
    include-in-header: meta.html
    footnotes-hover: true
    fig-cap-location: margin
    reference-location: margin
    highlight-style: github
    code-line-numbers: true

execute:
  freeze: auto
  
comments:
  giscus:
    repo: atsyplenkov/quarto-blog


